[package]

name = "tinyrick"
description = "a freeform Rust build system"
version = "0.0.5"
authors = ["Andrew Pennebaker <andrew.pennebaker@gmail.com>"]
license = "BSD-2-Clause"
homepage = "https://github.com/mcandre/tinyrick"
documentation = "https://docs.rs/tinyrick/"

[lib]
name = "tinyrick"

[[bin]]
name = "tinyrick"
path = "src/tinyrick.rs"
